### ISSUE TITLE
`npx reqover serve` сrashes

### ISSUE THREAD

**Issue by Twilighters** [reqover/reqover-python#6]
When using command `npx reqover serve` сrashes with an error:

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1432:16)
    at listenInCluster (node:net:1480:12)
    at Server.listen (node:net:1568:7)
    at serveFolder (C:\Users\TwS\AppData\Local\npm-cache\_npx\e8ee9637c159e8cb\node_modules\reqover\dist\server.js:1:1423)
    at Object.handler (C:\Users\TwS\AppData\Local\npm-cache\_npx\e8ee9637c159e8cb\node_modules\reqover\dist\index.js:2:3309)
    at C:\Users\TwS\AppData\Local\npm-cache\_npx\e8ee9637c159e8cb\node_modules\yargs\build\index.cjs:1:8891
    at j (C:\Users\TwS\AppData\Local\npm-cache\_npx\e8ee9637c159e8cb\node_modules\yargs\build\index.cjs:1:4956)
    at M.handleValidationAndGetResult (C:\Users\TwS\AppData\Local\npm-cache\_npx\e8ee9637c159e8cb\node_modules\yargs\build\index.cjs:1:8860)
    at M.applyMiddlewareAndGetResult (C:\Users\TwS\AppData\Local\npm-cache\_npx\e8ee9637c159e8cb\node_modules\yargs\build\index.cjs:1:9502)
    at M.runCommand (C:\Users\TwS\AppData\Local\npm-cache\_npx\e8ee9637c159e8cb\node_modules\yargs\build\index.cjs:1:7231)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1459:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v18.7.0
```

**Comment by Twilighters** [comment]
need to create server
